"""Generate urdf/arm.xacro from the vendored upstream SO-101 URDF.

This is a TEXT-level transform, deliberately. Every origin/limit/inertia string
is carried over byte-for-byte from upstream, so the result can be diffed
against a future SO-ARM100 release without spurious float-formatting noise, and
so no number can be mistyped on the way in.

Transforms applied (brief section 5.1-5.3):
  * link names            -> ${prefix}<name>          (prefix defaults to arm_)
  * joint names           -> UNCHANGED. A LeRobot policy is trained against
                             this exact action space, so the 6 movable joint
                             names must survive verbatim.
  * visual mesh paths     -> package://mmr_pkg/meshes/arm/<f>.stl
  * collision mesh paths  -> package://mmr_pkg/meshes/collision/arm/<f>.stl
                             (upstream aims collision at the full-detail visual
                             mesh, which section 4 forbids)
  * <transmission> blocks -> dropped. These are ROS 1
                             hardware_interface/PositionJointInterface tags;
                             Jazzy uses <ros2_control>, added in Phase 2.
  * stray <origin> inside <link name="gripper_frame_link"> -> dropped, it is
                             not valid URDF and is silently ignored anyway.

The output is verified against the input afterwards: same link set (modulo
prefix), same joint names, same joint types, same limits.
"""
import re
import xml.etree.ElementTree as ET

SRC = "tools/upstream/so101_new_calib.urdf"
DST = "urdf/arm.xacro"
PKG = "mmr_pkg"

raw = open(SRC, encoding="utf-8").read()

# ---- collect the upstream link names so we only rewrite real ones ----
up = ET.fromstring(raw)
LINKS = [l.get("name") for l in up.findall("link")]
JOINTS = {j.get("name"): j for j in up.findall("joint")}
print(f"upstream: {len(LINKS)} links, {len(JOINTS)} joints")

body = raw

# 1. drop the XML decl / <robot> wrapper / materials - re-emitted by hand below
body = body.split("<robot", 1)[1].split(">", 1)[1]
body = body.rsplit("</robot>", 1)[0]

# 2. drop <transmission> ... </transmission>
body, n_trans = re.subn(r"[ \t]*<transmission\b.*?</transmission>\s*?\n",
                        "", body, flags=re.S)

# 3. drop the material definitions (re-emitted outside the macro so that
#    instantiating the macro twice cannot redefine them)
body = re.sub(r"[ \t]*<!-- Materials -->\s*\n", "", body)
body, n_mat = re.subn(r"[ \t]*<material name=\"(?:3d_printed|sts3215)\">"
                      r".*?</material>\s*?\n", "", body, flags=re.S)

# 4. drop the stray <origin> that sits directly under gripper_frame_link
body, n_org = re.subn(
    r"(<link name=\"gripper_frame_link\">\s*\n)[ \t]*<origin[^/]*/>\s*\n",
    r"\1", body)

# 5. prefix link names (definitions and every parent/child reference)
n_ref = 0
for ln in LINKS:
    body, a = re.subn(rf"(<link name=\")({re.escape(ln)})(\")",
                      r"\1${prefix}\2\3", body)
    body, b = re.subn(rf"(<(?:parent|child) link=\")({re.escape(ln)})(\")",
                      r"\1${prefix}\2\3", body)
    n_ref += a + b

# 6. mesh paths - collision first, so the visual rule cannot claim them
def _mesh(m, sub):
    return f'<mesh filename="package://{PKG}/meshes/{sub}/{m}"/>'


body, n_coll = re.subn(
    r"(<collision>.*?)<mesh filename=\"assets/([^\"]+)\"\s*/>",
    lambda m: m.group(1) + _mesh(m.group(2), "collision/arm"), body, flags=re.S)
body, n_vis = re.subn(
    r"<mesh filename=\"assets/([^\"]+)\"\s*/>",
    lambda m: _mesh(m.group(1), "arm"), body)

print(f"dropped {n_trans} transmissions, {n_mat} materials, {n_org} stray origin")
print(f"prefixed {n_ref} link refs; rewrote {n_vis} visual + {n_coll} collision meshes")
assert re.search(r"assets/", body) is None, "an assets/ path survived"

# re-indent the vendored body one level deeper (it now lives inside a macro)
body = "\n".join(("  " + l if l.strip() else l) for l in body.split("\n"))

HEAD = f"""<?xml version="1.0"?>
<!-- ==================================================================== -->
<!-- SO-101 arm, vendored from TheRobotStudio/SO-ARM100                    -->
<!--   source: Simulation/SO101/so101_new_calib.urdf                       -->
<!--   GENERATED by tools/gen_arm_xacro.py - do not hand-edit.             -->
<!--                                                                       -->
<!-- Joint names are deliberately NOT prefixed: a LeRobot policy is        -->
<!-- trained against this exact action space. Link names ARE prefixed to   -->
<!-- avoid colliding with the chassis root, which is also called           -->
<!-- base_link upstream.                                                   -->
<!-- ==================================================================== -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <material name="3d_printed">
    <color rgba="1.0 0.82 0.12 1.0"/>
  </material>
  <material name="sts3215">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- prefix : name prefix for every arm LINK (not joints)
       parent : link the arm bolts to
       *origin: mount transform, parent -> ${{prefix}}base_link -->
  <xacro:macro name="so101_arm" params="prefix parent *origin">

    <joint name="${{prefix}}base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${{parent}}"/>
      <child link="${{prefix}}base_link"/>
    </joint>
"""

TAIL = """
  </xacro:macro>
</robot>
"""

open(DST, "w", encoding="utf-8").write(HEAD + body.rstrip() + "\n" + TAIL)
print(f"wrote {DST}")

# ------------------------------------------------------------------ verify
txt = open(DST, encoding="utf-8").read()
chk = ET.fromstring(txt.replace("${prefix}", "P_").replace(
    "${parent}", "P_parent").replace(
    '<xacro:insert_block name="origin"/>', ""))
mac = chk.find("{http://www.ros.org/wiki/xacro}macro")
got_links = [l.get("name") for l in mac.findall("link")]
got_joints = {j.get("name"): j for j in mac.findall("joint")}

assert got_links == ["P_" + l for l in LINKS], got_links
print(f"OK  links match upstream ({len(got_links)})")

extra = set(got_joints) - set(JOINTS)
assert extra == {"P_base_joint"}, extra
assert set(JOINTS) <= set(got_joints), set(JOINTS) - set(got_joints)
print(f"OK  joint names preserved verbatim ({len(JOINTS)}) + P_base_joint")

for name, j in JOINTS.items():
    g = got_joints[name]
    assert g.get("type") == j.get("type"), name
    lu, lg = j.find("limit"), g.find("limit")
    assert (lu is None) == (lg is None), name
    if lu is not None:
        assert lu.attrib == lg.attrib, f"{name}: {lu.attrib} != {lg.attrib}"
    ou, og = j.find("origin"), g.find("origin")
    assert ou.attrib == og.attrib, name
print("OK  joint types, limits and origins identical to upstream")

mov = [n for n, j in got_joints.items() if j.get("type") != "fixed"]
print(f"OK  {len(mov)} movable arm joints: {sorted(mov)}")
